server:
  port: 8000

spring:
  application:
    name: fashionhub

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**


